
#ウインドウのインデックスを1から始める
set -g base-index 1

#ペインのインデックスを1から始める
set -g pane-base-index 1

#プレフィックスキーをCtrl + b から Ctrl + qに変更
set -g prefix C-a
unbind C-b

# \で垂直分割、- で水平分割
bind '\' split-window -h
bind '-' split-window -v

#マウス操作を有効化(クリックで画面選択、ドラッグでリサイズ可能")
set -g mouse on

# 256色表示を有効化
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# vim風のキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


#ステータスバーのデザインをシンプルに
set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"
set -g status-right "%m/%d %H:%M"

#ウインドウ番号を常に表示
set-option -g renumber-windows on
